// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwef7yVTCB0CO015SNaa9LK_zJoUoRkhw',
    appId: '1:970098471354:web:1ff53a88a4bb741b4a2d83',
    messagingSenderId: '970098471354',
    projectId: 'mynotes-aks777',
    authDomain: 'mynotes-aks777.firebaseapp.com',
    storageBucket: 'mynotes-aks777.appspot.com',
    measurementId: 'G-19NWFXQR06',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF1pw72WZ3m-sPRmTCyPfAegATHlw0VP0',
    appId: '1:970098471354:android:7f0102f670bbb8294a2d83',
    messagingSenderId: '970098471354',
    projectId: 'mynotes-aks777',
    storageBucket: 'mynotes-aks777.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY6Sj5EFbiTe3mJL7lQ_F5Y1-0JKZr3mM',
    appId: '1:970098471354:ios:1098647082a4e0bc4a2d83',
    messagingSenderId: '970098471354',
    projectId: 'mynotes-aks777',
    storageBucket: 'mynotes-aks777.appspot.com',
    iosClientId: '970098471354-f21cqraol774t5v1ndngacifgse1uqjg.apps.googleusercontent.com',
    iosBundleId: 'com.ashishks777.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDY6Sj5EFbiTe3mJL7lQ_F5Y1-0JKZr3mM',
    appId: '1:970098471354:ios:1098647082a4e0bc4a2d83',
    messagingSenderId: '970098471354',
    projectId: 'mynotes-aks777',
    storageBucket: 'mynotes-aks777.appspot.com',
    iosClientId: '970098471354-f21cqraol774t5v1ndngacifgse1uqjg.apps.googleusercontent.com',
    iosBundleId: 'com.ashishks777.mynotes',
  );
}
